version: '3'
services:
  mysql:
    container_name: db_mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: projectmanager
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    expose:
      - 3306
  backend:
    container_name: go-rest-api
    depends_on:
        mysql:
          condition: service_healthy
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      WAIT_HOSTS: mysql:3306
    ports:
      - "8080:8080"
